#!/bin/bash
SHELL=/bin/bash

# One optional argument is hardware name
TOOLNAME=Hauntimator
if [ $# -gt 0 ]; then
    TOOLNAME=$1
fi

# Get path to this script and thus to the install directory
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo Path:$SCRIPTPATH

# Set up the virtual environment
cd $SCRIPTPATH
python3 -m venv --system-site-packages .venv
CODE=$?
if [ $CODE -ne 0 ]; then
    echo WHOOPS - Need to install venv tools
    exit $CODE
fi
source .venv/bin/activate

# Install and update dependencies
pip install -U pip
pip install -U PyQt5
CODE=$?
if [ $CODE -ne 0 ]; then
    echo WHOOPS - Need to install PyQt6
    pip install -U PyQt6==6.5
    CODE=$?
    if [ $CODE -ne 0 ]; then
        echo WHOOPS - Unable to install PyQt
        exit $CODE
    fi
fi
pip install -U PythonQwt
pip install -U pygame-ce
pip install -U rshell

echo
echo -n 'Do you want to install phoneme-based speech recognition tools (y/N)? '
read answer
if [ $answer == 'y' ]; then
    echo Installing vosk python module
    pip install -U vosk

    pushd $SCRIPTPATH/src/plugins/Phoneme_data

    echo
    echo Installing vosk American English language model
    curl https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip -o ~/Downloads/vosk-model-small-en-us-0.15.zip
    unzip ~/Downloads/vosk-model-small-en-us-0.15.zip
    rm -f vosk-model
    ln -s vosk-model-small-en-us-0.15 vosk-model

    echo
    echo Installing CMU Phoneme dictionary
    curl https://svn.code.sf.net/p/cmusphinx/code/trunk/cmudict/sphinxdict/cmudict_SPHINX_40 -O
    ln -s cmudict_SPHINX_40 dictionary
    popd
else
    pushd $SCRIPTPATH/src/plugins
    rm -rf Phoneme*
    popd
fi


# Make runnables that don't need venv
cat << EOF > ${SCRIPTPATH}/Hauntimator
#!/bin/bash
# Need to be in a user directory when creating autosave file
cd ~

${VIRTUAL_ENV}/bin/python3 ${SCRIPTPATH}/src/Hauntimator.py "\$@"
if [ \$? -ne 0 ]; then
    echo Whoops - Hauntimator pulled an error
    echo Since this should NEVER happen, you might want to take a screenshot
    echo or copy the output, if any, and submit it with a bug report.
    echo
    read -n 1 -s -r -p "Press any key to continue..."
fi
EOF

chmod +x ${SCRIPTPATH}/Hauntimator

cat << EOF > ${SCRIPTPATH}/joysticking
#!$SHELL

${VIRTUAL_ENV}/bin/python3 ${SCRIPTPATH}/src/joysticking.py "\$@"
EOF

chmod +x ${SCRIPTPATH}/joysticking

cat << EOF > ${SCRIPTPATH}/Pico/rshell
#!$SHELL

${VIRTUAL_ENV}/bin/rshell "\$@"
EOF

chmod +x ${SCRIPTPATH}/Pico/rshell

cat << EOF > ${SCRIPTPATH}/Pico/verifyload
#!$SHELL

${VIRTUAL_ENV}/bin/python3 ${SCRIPTPATH}/Pico/verifyload.py "\$@"
EOF

chmod +x ${SCRIPTPATH}/Pico/verifyload

cat << EOF > ${SCRIPTPATH}/Maestro_Animator
#!$SHELL

export PYTHONPATH=${SCRIPTPATH}/Pololu:${SCRIPTPATH}/Pololu/lib

${VIRTUAL_ENV}/bin/python3 ${SCRIPTPATH}/src/Maestro_Animator.py "\$@"
EOF

chmod +x ${SCRIPTPATH}/Maestro_Animator

# Create desktop links to run Hauntimator and joysticking
if [ -d ~/Desktop ]; then
    echo
    echo -n 'Do you want to install desktop icons (y/N)? '
    read answer
    if [ $answer == 'y' ]; then
        if [ $OSTYPE == 'darwin' ]; then

            # Function for creating desktop apps
            create_shortcut() {
                # Create an applescript file to run the app
                cat << EOF > tmp.applescript
on open droppedItems
    repeat with anItem in droppedItems
        set p to POSIX path of anItem
        do shell script quoted form of "${SCRIPTPATH}/$1" & " -a " & quoted form of p
    end repeat
end open

on run
    do shell script quoted form of "${SCRIPTPATH}/$1"
end run
EOF
                # Compile the script into the desktop shortcut
                osacompile -o ~/Desktop/${2}.app tmp.applescript
                # Attach the icon
                cp $3 ~/Desktop/${2}.app/Contents/Resources/droplet.icns
                touch ~/Desktop/${2}.app
                # Remove the temp file
                rm -f tmp.applescript
            }
            # Create shortcut for Hauntimator
            create_shortcut "Hauntimator" "$TOOLNAME" "${SCRIPTPATH}/src/docs/images/Hlogo.icns"
            if [ -z "$1" ] || [ "$1" = "Pololu" ]; then
                # Create shortcut for Maestro_Animator
                create_shortcut "Maestro_Animator" "Maestro_Animator" "${SCRIPTPATH}/src/docs/images/CElogo.icns"
            fi
        elif [ ${OSTYPE:0:5} == linux ]; then
            cat << EOF > ~/Desktop/${TOOLNAME}.desktop
[Desktop Entry]
Version=__VERSION__
Type=Application
Terminal=true
Exec=${SCRIPTPATH}/Hauntimator -a %f
Name=${TOOLNAME}
Comment=Hauntimator Version: __VERSION__
Icon=${SCRIPTPATH}/src/docs/images/Hlogo.png
EOF

            touch ~/Desktop/${TOOLNAME}.desktop
            if [ -z "$1" ] || [ "$1" = "Pololu" ]; then
                cat << EOF > ~/Desktop/Maestro_Animator.desktop
[Desktop Entry]
Version=__VERSION__
Type=Application
Terminal=true
Exec=${SCRIPTPATH}/Maestro_Animator -a %f
Name=Maestro_Animator
Comment=Animator Version: __VERSION__
Icon=${SCRIPTPATH}/src/docs/images/CElogo.png
EOF

                touch ~/Desktop/Maestro_Animator.desktop
            fi
        fi
    fi
fi

# Go back where we came from
cd ${SCRIPTPATH}
