#!/bin/bash
SHELL=/bin/bash

# No arguments

# Get path to this script and thus to the install directory
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo Path:$SCRIPTPATH

# Set up the virtual environment
cd $SCRIPTPATH
python3 -m venv --system-site-packages .venv
CODE=$?
if [ $CODE -ne 0 ]; then
    echo WHOOPS - Need to install venv tools
    exit $CODE
fi
source .venv/bin/activate

# Install and update dependencies
pip install -U pip
pip install -U PyQt5
CODE=$?
if [ $CODE -ne 0 ]; then
    echo WHOOPS - Need to install PyQt6
    pip install -U PyQt6==6.5
    CODE=$?
    if [ $CODE -ne 0 ]; then
        echo WHOOPS - Unable to install PyQt
        exit $CODE
    fi
fi
pip install -U PythonQwt
pip install -U pygame-ce
pip install -U rshell
pip install -U pocketsphinx

# Make runnables that don't need venv
cat << EOF > ${SCRIPTPATH}/Hauntimator
#!$SHELL

${VIRTUAL_ENV}/bin/python3 ${SCRIPTPATH}/src/Hauntimator.py "\$@"
EOF

chmod +x ${SCRIPTPATH}/Hauntimator

cat << EOF > ${SCRIPTPATH}/joysticking
#!$SHELL

${VIRTUAL_ENV}/bin/python3 ${SCRIPTPATH}/src/joysticking.py "\$@"
EOF

chmod +x ${SCRIPTPATH}/joysticking

cat << EOF > ${SCRIPTPATH}/Pico/rshell
#!$SHELL

${VIRTUAL_ENV}/bin/rshell "\$@"
EOF

chmod +x ${SCRIPTPATH}/Pico/rshell

cat << EOF > ${SCRIPTPATH}/Pico/verifyload
#!$SHELL

${VIRTUAL_ENV}/bin/python3 ${SCRIPTPATH}/Pico/verifyload.py "\$@"
EOF

chmod +x ${SCRIPTPATH}/Pico/verifyload

cat << EOF > ${SCRIPTPATH}/Maestro_Animator
#!$SHELL

export PYTHONPATH=${SCRIPTPATH}/Pololu:${SCRIPTPATH}/Pololu/lib

${VIRTUAL_ENV}/bin/python3 ${SCRIPTPATH}/src/Maestro_Animator.py "\$@"
EOF

chmod +x ${SCRIPTPATH}/Maestro_Animator

# Create desktop links to run Hauntimator and joysticking
if [ -d ~/Desktop ]; then
    echo -n 'Do you want to install desktop icons (y/N)? '
    read answer
    if [ $answer == 'y' ]; then
        if [ $OSTYPE == 'darwin' ]; then
            if [ -e ~/Desktop/Untitled.app ]; then
                # Create apps from existing structure
                cd ${SCRIPTPATH}/src
                cp -r ~/Desktop/Untitled.app appdir
                rm -f appdir/Contents/Resources/ApplicationStub.icns
                cp -f docs/images/Hicon.icns appdir/Contents/Resources/ApplicationStub.icns
                sed -i '' -e "s%>cat<%>${SCRIPTPATH}/Hauntimator -f \$1<%g" appdir/Contents/document.wflow
                rm -rf ~/Desktop/Hauntimator.app
                mv appdir ~/Desktop/Hauntimator.app

                cp -r ~/Desktop/Untitled.app appdir
                rm -f appdir/Contents/Resources/ApplicationStub.icns
                cp -f docs/images/CEicon.icns appdir/Contents/Resources/ApplicationStub.icns
                sed -i '' -e "s%>cat<%>${SCRIPTPATH}/Maestro_Animator<%g" appdir/Contents/document.wflow
                rm -rf ~/Desktop/Maestro_Animator.app
                mv appdir ~/Desktop/Maestro_Animator.app
            fi
        elif [ ${OSTYPE:0:5} == linux ]; then
            cat << EOF > ~/Desktop/Hauntimator.desktop
[Desktop Entry]
Version=__VERSION__
Type=Application
Terminal=true
Exec=${SCRIPTPATH}/Hauntimator -f %f
Name=Hauntimator
Comment=Hauntimator Version: __VERSION__
Icon=${SCRIPTPATH}/src/docs/images/Hlogo.png
EOF

            cat << EOF > ~/Desktop/Maestro_Animator.desktop
[Desktop Entry]
Version=__VERSION__
Type=Application
Terminal=true
Exec=${SCRIPTPATH}/Maestro_Animator -p %f
Name=Maestro_Animator
Comment=joysticking Version: __VERSION__
Icon=${SCRIPTPATH}/src/docs/images/CElogo.png
EOF
        fi
    fi
fi

# Clean up some unwanted things
cd ${SCRIPTPATH}
