#!/bin/bash

# No arguments

# Get path to this script and thus to the install directory
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo Uninstalling $SCRIPTPATH

# Delete everything
cd $SCRIPTPATH/..
rm -rf $SCRIPTPATH

# Make for loops skip if empty
shopt -s nullglob

# Remove linux desktop icons that point to this repo
for f in ~/Desktop/*.desktop; do
    grep -q "$SCRIPTPATH" $f
    CODE=$?
    if [ $CODE -eq 0 ]; then
        rm -f $f
    fi
done

# Remove MacOS desktop icons that point to this repo
for f in ~/Desktop/*.app; do
    if [ -e ${f}/Contents/document.wflow ]; then
        grep -q "$SCRIPTPATH" ${f}/Contents/document.wflow
        CODE=$?
        if [ $CODE -eq 0 ]; then
            rm -rf $f
        fi
    fi
done

