#!/bin/bash

# No arguments

# Get path to this script and thus to the install directory
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
echo Uninstalling $SCRIPTPATH

# Make for loops skip if empty
shopt -s nullglob

# Remove linux desktop icons that point to this repo
for f in ~/Desktop/*.desktop; do
    grep -q "$SCRIPTPATH" $f
    CODE=$?
    if [ $CODE -eq 0 ]; then
        rm -f $f
    fi
done

# Remove MacOS desktop icons that point to this repo
for f in ~/Desktop/*.app; do
    for g in ${f}/Contents/Resources/Scripts/*.scpt; do
        if osadecompile $g 2>/dev/null | grep -qi "$SCRIPTPATH"; then
            rm -rf $f
        fi
    done
done

# Delete everything
cd $SCRIPTPATH/..
rm -rf $SCRIPTPATH

