#!/bin/csh -f
#set echo

rshell mkdir /pyboard/lib
rshell cp Halloween_helpers.py /pyboard/lib/helpers.py
rshell cp servo.py /pyboard/lib
rshell cp wave.py /pyboard/lib
rshell cp main.py /pyboard
rshell cp memstats.py /pyboard/lib
rshell mkdir /pyboard/anims

echo ''
echo ''

# Check on the results
rshell repl '~ import memstats ~'
