#!/bin/bash
#set echo

# Get path to this script
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# make it the working directory
pushd $SCRIPTPATH

# Need to be in virtual environment to use rshell
source ../.venv/bin/activate

# Check to make sure tabledefs has been created
echo Validating local tabledefs
python3 lib/tables.py  >& /dev/null
CODE=$?
if [ $CODE -ne 0 ]; then
    echo
    echo Whoops - problems with tabledefs file - aborting
    echo Results of check are:
    python3 lib/tables.py -r -v
    exit
fi

# Determine which rshell to use
echo Checking rshell
rshell=rshell
which rshell >& /dev/null
CODE=$?
if [ $CODE -ne 0 ]; then
    echo Whoops - Unable to find rshell tool needed for installation
    echo Perhaps you have not run install in the top directory
    exit 10
fi

# Get the port used by rshell - we assume it is first in the list
port=$(${rshell} -l | grep -i 2e8a | sed -e 's/^[^@]*@//' -e 's/ .*//' -e 's%/cu\.%/tty.%')
echo Using port: $port >& /dev/null

if [ -z "$port" ]; then
    echo 'WHOOPS - Unable to locate Pico on USB port - Aborting'
    exit 10
fi

echo -n 'Do you want to remove all existing animations (y/N)? '
read answer
if [ $answer == 'y' ]; then
    echo Removing existing animations '(Make take more than 1 minute)'
    ${rshell} --quiet rm '/pyboard/sd/anims/*'
    ${rshell} --quiet rm '/pyboard/anims/*'
fi

echo Prepping Pico filesystem
${rshell} --quiet rm /pyboard/boot.py >& /dev/null
${rshell} --quiet repl '~ import machine ~ machine.reset() ~' >& /dev/null
sleep 5

echo Installing libraries
${rshell} --quiet mkdir /pyboard/lib >& /dev/null
${rshell} --quiet mkdir /pyboard/anims >& /dev/null
${rshell} --quiet cp lib/servo.py \
          lib/wave.py \
          lib/pca9685.py \
          lib/sdcard.py \
          lib/memstats.py \
          lib/tables.py \
          lib/tabledefs \
          lib/helpers.py \
          lib/maestro.py \
          /pyboard/lib
echo Installing main.py
${rshell} --quiet cp main.py /pyboard

echo ''
echo ''
echo -n 'Install demo/diagnostic animations (y/N):'
read reply
echo ''
if [ $reply = 'y' ] || [ $reply = 'Y' ]; then
    ${rshell} --quiet cp anims/* /pyboard/anims
fi

# Check on the results
${rshell} --quiet repl '~ import memstats ~' >& /dev/null

# Install boot.py last as rshell runs really slowly once it's there
echo Installing boot.py
${rshell} --quiet cp boot.py /pyboard

# Record the port locally for commlib to pick up
echo -n $port > .portid

# Reboot the Pico
echo Resetting Pico
${rshell} --quiet repl '~ import machine ~ machine.reset() ~' >& /dev/null

# Wait a couple of seconds for Pico to restart running main
sleep 5

# Verify installation
echo
echo Verifying installation
echo
if [ -f ./verifyload ]; then
    ./verifyload -p $port
else
    python3 verifyload.py -p $port
fi

CODE=$?
if [ $CODE -eq 0 ]; then
    echo All python files validate
fi

# Validate installed diagnostic animations
if [ $reply = 'y' ] || [ $reply = 'Y' ]; then
    echo ''
    # Used to fail for .wav files due to short timeout but now fixed
    if [ -f ./verifyload ]; then
        ./verifyload -p $port -fl `ls anims/*`
    else
        python3 verifyload.py -p $port -fl `ls anims/*`
    fi
    CODE=$?
    if [ $CODE -eq 0 ]; then
        echo Diagnostic anim files validate
    fi
fi

exit 0
